//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class InStock
    {
        public int Sid { get; set; }
        public int Pid { get; set; }
        public int Wid { get; set; }
        public string Wieght { get; set; }
        public string Milliltion { get; set; }
        public string CaseSize { get; set; }
        public Nullable<System.DateTime> InStockDate { get; set; }
        public string Note { get; set; }
    }
}
