//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        [Display(Name ="訂單編號")]
        public int OrderID { get; set; }
        [Display(Name = "酒莊")]
        public Nullable<int> WineryID { get; set; }
        [Display(Name = "客戶名稱")]
        public string CustomerName { get; set; }
        [Display(Name = "訂購時間")]
        public Nullable<System.DateTime> OrderDate { get; set; }
        [Display(Name = "時間")]
        public Nullable<System.DateTime> RequiredDate { get; set; }
        [Display(Name = "出貨時間")]
        public Nullable<System.DateTime> ShippedDate { get; set; }
        [Display(Name = "備註")]
        public string Note { get; set; }
    
        public virtual Order_Details Order_Details { get; set; }
        public virtual Winery Winery { get; set; }
    }
}
