//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StockEnter
    {
        public int StockEnterID { get; set; }
        public int ProductID { get; set; }
        public int WineryID { get; set; }
        public int ShelfID { get; set; }
        public int MilliliterID { get; set; }
        public int Quantity { get; set; }
        public string Note { get; set; }
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> StockEnterDate { get; set; }
    
        public virtual Milliliter Milliliter { get; set; }
        public virtual Product Product { get; set; }
        public virtual Shelf Shelf { get; set; }
        public virtual Winery Winery { get; set; }
    }
}
