//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    [ValidateAntiForgeryToken]
    public partial class Account
    {
        [Display(Name = "序號")]
        [Required]
        public int AccountId { get; set; }
        [Display(Name = "帳號")]
        [Required]
        public string Account1 { get; set; }
        [Display(Name = "密碼")]
        [Required]
        [Editable(true)]
        public string Password { get; set; }
        [Display(Name = "識別碼")]
        [Required]
        public string IdentityCode { get; set; }
        [Display(Name = "酒莊序號")]
        [Required]
        public int WineryID { get; set; }
    
        public virtual Winery Winery { get; set; }
    }
}
