//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class DELogisticsEntities : DbContext
    {
        public DELogisticsEntities()
            : base("name=DELogisticsEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<Milliliter> Milliliter { get; set; }
        [JsonIgnore]
        public virtual DbSet<Order> Order { get; set; }
        [JsonIgnore]
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Shelf> Shelf { get; set; }
        public virtual DbSet<StockEnter> StockEnter { get; set; }
        public virtual DbSet<Winery> Winery { get; set; }
    }
}
